---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "test"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for testing only."
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for linting only."
resolutions:
  rule_violations:
    # ERRORS (NO_LICENSE_IN_DEPENDENCY)
    - message: ".*PyPI::fastapi:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/fastapi/blob/master/LICENSE"
    - message: ".*PyPI::starlette:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/Kludex/starlette/blob/main/LICENSE.md"
    - message: ".*PyPI::pydantic:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic/blob/main/LICENSE"
    - message: ".*PyPI::pydantic-core:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic-core/blob/main/LICENSE"
    - message: ".*PyPI::typing-inspection:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/typing-inspection/blob/main/LICENSE"
    - message: ".*PyPI::typing-extensions:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Same as CPython: https://github.com/python/typing_extensions/blob/4.14.0/LICENSE"
    - message: ".*PyPI::uvicorn:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/Kludex/uvicorn/blob/main/LICENSE.md"
    - message: ".*PyPI::anyio:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/agronholm/anyio/blob/master/LICENSE"
    - message: ".*PyPI::annotated-doc:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/annotated-doc/blob/main/LICENSE"
    - message: ".*PyPI::httpcore:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/master/LICENSE.md"
    - message: ".*PyPI::cryptography:46\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0 and BSD-3 License: https://github.com/pyca/cryptography/?tab=Apache-2.0-2-ov-file"
    - message: ".*PyPI::cffi:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-cffi/cffi/blob/main/LICENSE"
    - message: ".*PyPI::azure-identity:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/Azure/azure-sdk-for-python/blob/main/LICENSE"
    - message: ".*PyPI::pyjwt:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/jpadilla/pyjwt/blob/master/LICENSE"
    - message: ".*PyPI::urllib3:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/urllib3/urllib3/blob/2.5.0/LICENSE.txt"
    - message: ".*PyPI::attrs:25\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-attrs/attrs/blob/main/LICENSE"
    - message: ".*PyPI::packaging:26\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Dual (APL-2.0 & BSD-2): https://github.com/pypa/packaging/blob/main/LICENSE"
    - message: ".*PyPI::markupsafe:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pallets/markupsafe/blob/main/LICENSE.txt"
    - message: ".*PyPI::isodate:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD License: https://github.com/gweis/isodate/blob/master/LICENSE"
    - message: ".*PyPI::setuptools:82\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pypa/setuptools/blob/main/LICENSE"
    - message: ".*PyPI::pygments:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD-2-Clause License: https://github.com/pygments/pygments/blob/master/LICENSE"
    - message: ".*PyPI::aidial-sdk:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/epam/ai-dial-sdk/blob/development/LICENSE"
    - message: ".*PyPI::black:26\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/psf/black/blob/main/LICENSE"
    - message: ".*PyPI::nox:2026\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/wntrblm/nox/blob/main/LICENSE"
    - message: ".*PyPI::dependency-groups:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pypa/dependency-groups/blob/main/LICENSE"
    - message: ".*PyPI::termcolor:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/termcolor/termcolor/blob/main/COPYING.txt"
    - message: ".*PyPI::humanize:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-humanize/humanize/blob/main/LICENCE"
    - message: ".*PyPI::pytest-asyncio:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/pytest-dev/pytest-asyncio/blob/main/LICENSE"
    - message: ".*PyPI::pytest-timeout:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/pytest-timeout/blob/main/LICENSE"

    # WARNINGS (UNMAPPED_DECLARED_LICENSE)
    - message: ".*PyPI::traitlets:5\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/ipython/traitlets/blob/main/LICENSE"
    - message: ".*PyPI::backcall:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/takluyver/backcall/blob/master/LICENSE"
    - message: ".*PyPI::prompt-toolkit:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/LICENSE"