include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

### Security scanning jobs
gemnasium-python-dependency_scanning:
  stage: security-scanning
  variables:
    DS_REMEDIATE: "false"
  artifacts:
    paths:
      - gl-dependency-scanning-report.json
      - gl-dependency-scanning-report-${CI_JOB_ID}.json
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  after_script:
    - ls *.json
    - cp -fv gl-dependency-scanning-report.json gl-dependency-scanning-report-${CI_JOB_ID}.json
  rules:
    - when: always
  tags:
    - DockerExecutor

semgrep-sast:
  stage: security-scanning
  artifacts:
    paths:
      - gl-sast-report.json
      - gl-sast-report-${CI_JOB_ID}.json
    reports:
      sast: gl-sast-report.json
  after_script:
    - ls *.json
    - cp -fv gl-sast-report.json gl-sast-report-${CI_JOB_ID}.json
  rules:
    - when: always
  tags:
    - DockerExecutor

secret_detection:
  stage: security-scanning
  artifacts:
    paths:
      - gl-secret-detection-report.json
      - gl-secret-detection-report-${CI_JOB_ID}.json
    reports:
      secret_detection: gl-secret-detection-report.json
  after_script:
    - ls *.json
    - cp -fv gl-secret-detection-report.json gl-secret-detection-report-${CI_JOB_ID}.json
  rules:
    - when: always
  tags:
    - DockerExecutor

container_scanning:
  stage: publish
  needs:
    - publish
  variables:
    GIT_STRATEGY: none
    CS_IMAGE: ${REPOSITORY}/${DOCKER_PATH}:${DOCKER_TAG}
    CS_REGISTRY_USER: ${ARTIFACTORY_USER}
    CS_REGISTRY_PASSWORD: ${ARTIFACTORY_PASS}
  dependencies: []
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH  == "development"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        DOCKER_ADDITIONAL_TAG: alpha
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"'
      when: never
  tags:
    - AWS
    - DockerExecutor
### END Security scanning jobs

### Security scanning reports validation jobs
scanning_reports_validation:
  stage: scanning-reports-validation
  allow_failure: true
  rules:
    - when: never
  script:
    - SCANNING_REPORT_PATH=$(find . -name "${SCANNING_REPORT_NAME}-*.json")
    - SCAN_JOB_ID=$(echo "${SCANNING_REPORT_PATH}" | grep -o '[0-9]\+')
    - |
      if [ "$(jq ".vulnerabilities | length" ${SCANNING_REPORT_PATH})" -gt 0 ]; then
        echo "Vulnerabilities detected. Please analyze the artifact ${CI_PROJECT_URL}/-/jobs/${SCAN_JOB_ID}/artifacts/file/${SCANNING_REPORT_NAME}.json  produced by the ${SCANNING_JOB_NAME} job."
        exit 1
      fi
  tags:
    - DockerExecutor

dependency_scanning_reports_validation:
  extends:
    - scanning_reports_validation
  needs:
    - gemnasium-python-dependency_scanning
  dependencies:
    - gemnasium-python-dependency_scanning
  variables:
    SCANNING_REPORT_NAME: gl-dependency-scanning-report
    SCANNING_JOB_NAME: gemnasium-python-dependency_scanning
  rules:
    - when: always

sast_reports_validation:
  extends:
    - scanning_reports_validation
  needs:
    - semgrep-sast
  dependencies:
    - semgrep-sast
  variables:
    SCANNING_REPORT_NAME: gl-sast-report
    SCANNING_JOB_NAME: semgrep-sast
  rules:
    - when: always

secret_detection_reports_validation:
  extends:
    - scanning_reports_validation
  needs:
    - secret_detection
  dependencies:
    - secret_detection
  variables:
    SCANNING_REPORT_NAME: gl-secret-detection-report
    SCANNING_JOB_NAME: secret_detection
  rules:
    - when: always
### END Security scanning reports validation jobs