image:
  pullPolicy: Always
  registry: registry-dev.deltixhub.com
  repository: ai/dial/application/dial-bing-grounding
  tag: development
  pullSecrets:
    - epm-rtc-registry-dev

fullnameOverride: "dial-bing-grounding"

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

containerSecurityContext:
  runAsUser: 1001

podSecurityContext:
  fsGroup: 1001

ingress:
  enabled: false

serviceAccount:
  create: true

env:
  PROJECT_CONNECTION_STRING: "eastus.api.azureml.ms;cac80694-eee4-49c2-963d-4789b6fa9867;sbx-dial-rg-weu;azure-ai-project-for-bing-ground"
  BING_CONNECTION_NAME: "binggroundingforopenai"
  LOG_LEVEL: "DEBUG"

  OTEL_RESOURCE_ATTRIBUTES: "service.name=dial-bing-grounding"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: "/health"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp,prometheus"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy-otel.monitoring.svc.cluster.local.:4317"