image:
  pullPolicy: Always
  registry: registry-dev.deltixhub.com
  repository: ai/dial/application/dial-bing-grounding
  tag: development
  pullSecrets:
    - epm-rtc-registry-dev

fullnameOverride: "dial-bing-grounding"

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

containerSecurityContext:
  runAsUser: 1001

podSecurityContext:
  fsGroup: 1001

ingress:
  enabled: false

podLabels:
  azure.workload.identity/use: "true"

serviceAccount:
  enabled: true
  name: dial-bing-grounding
  annotations:
    azure.workload.identity/client-id: 92f530bd-2a08-4068-9aec-6d68cd0b126d
  automountServiceAccountToken: false

env:
  AZURE_AI_PROJECT_CONNECTION_STRING: "eastus2.api.azureml.ms;e28e6b53-a7c2-4401-b95d-d8f803c1e582;epm-rtc;epm-rtc"
  BING_CONNECTION_NAME: "binggroundingforopenai"
  LOG_LEVEL: "DEBUG"

  OTEL_RESOURCE_ATTRIBUTES: "service.name=dial-bing-grounding"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  OTEL_PYTHON_FASTAPI_EXCLUDED_URLS: "/health"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp,prometheus"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy-otel.monitoring.svc.cluster.local.:4317"